# Generated by Django 3.2 on 2022-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_favourite_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_img',
            field=models.ImageField(blank=True, upload_to='banner_pics'),
        ),
    ]
