# Generated by Django 3.2 on 2022-06-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_edited_on',
            field=models.DateTimeField(blank=True, help_text='The date the review was last edited', null=True),
        ),
    ]
