# Generated by Django 3.2 on 2022-06-21 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Test Title', help_text='Title of the review', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.ForeignKey(help_text='The album this review is for', on_delete=django.db.models.deletion.CASCADE, to='reviews.album'),
        ),
    ]
