# Generated by Django 3.2 on 2022-08-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220621_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='date_formed',
            field=models.DateField(help_text='The year the artists started'),
        ),
    ]
