# Generated by Django 3.2 on 2022-08-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_artist_date_formed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='date_formed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
