# Generated by Django 3.2 on 2022-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcompany',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recordcompany',
            name='website',
            field=models.URLField(),
        ),
    ]
